name: Sync to Hugging Face model hub

on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git LFS
        uses: actions/checkout@v2
        with:
          ref: main # Set the branch ref to use for fetching LFS objects (optional)
          lfs: true # Enable Git LFS

      - name: Configure Git
        run: |
          git config user.name "Seyed Mohsen Sadeghi"
          git config user.email "m0hsnn@hotmail.com"
          git remote add hf https://huggingface.co/spaces/m0hsnn/MM-Movie-Recommender.git

      - name: Pull from Hugging Face model hub
        run: |
          git pull --rebase hf main

      - name: Push to Hugging Face model hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push hf HEAD:main
